hepsi:	derle	calistir

derle:

	
	g++ -I ./include/ -o ./lib/Node.o    -c ./src/Node.cpp
	g++ -I ./include/ -o ./lib/BinaryTree.o    		-c ./src/BinaryTree.cpp
	g++ -I ./include/ -o ./lib/Oyun.o    	-c ./src/Oyun.cpp
	g++ -I ./include/ -o ./lib/Test.o    		-c ./src/Test.cpp
	g++ ./lib/Node.o ./lib/BinaryTree.o ./lib/Oyun.o ./lib/Test.o -o ./bin/program
	
calistir:
	./bin/program